import os
import json
from mistralai.client import Mistral
from retrieve_context import build_context_block

client = Mistral(api_key=os.environ["MISTRAL_API_KEY"]) # reads anthropic key from .env

EXTRACTION_TOOL = {
"type": "function",
"function": {
  "name": "record_meeting_notes",
  "description": "Record structured notes and action items extracted from a meeting transcript",
  "parameters": {
    "type": "object",
    "properties": {
      "summary": {"type": "string"},
      "decisions": { "type": "array", "items": { "type": "string" }},
      "action_items": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "task": {"type": "string"},
                "owner": {"type": ["string", "null"]},
                "due_date": {"type": ["string", "null"]},
                "supporting_quote": {"type": "string"},
                "confidence": {"type": "string", "enum": ["high", "medium", "low"]}
            },
            "required": ["task", "supporting_quote", "confidence"]
        }
      }
    },
    "required": ["summary", "decisions", "action_items"]
    }
  }
}

def extract_notes (transcript: str) -> dict:
    context_block = build_context_block(transcript)

    SYSTEM_PROMPT = f"""You are a meeting notes assistant. You extract structured notes from meeting transcripts.

Use the context below from past meetings ONLY to check for updates or duplicate action items - DO NOT invent facts that aren't in the transcript. 

{context_block}

New transcript:

{transcript}

Rules for action items:
- Only include something as an action item if a specific person expicitly agreed to do it
- Do NOT extract information from context clues - only from explicit statements
- Do NOT include general information topics, suggestions, or things that were merely mentioned
- If a field is not explicitly stated in the text, set it to null
- Do NOT infer or guess values. If no due_date is stated, due_date must be null. 
- If no owner is stated by name, use null for owner - Do NOT infer or guess
- For supporting_quote, copy the exact sentence from the transcript that this action item is based on. Do NOT paraphrase it
- Set confidence to "low" if the action is implied rather than explicitly stated, high if it's unambiguous

Note: the transcript may contain transcription errors since it was generated by automatic speech recognition. Use context to work around minor errors, but do NOT invent context to fill gaps.

Respond ONLY with valid json matching this exact structure:
{{
"summary": "string",
"decisions": ["string"],
"action_items": [
    {{
        "task": "string",
        "owner": "string or null",
        "due_date": "string or null",
        "supporting_quote": "string",
        "confidence": "high, medium or low"
    }}]
}}
"""

    response = client.chat.complete(
        model="mistral-small-latest",
        messages=[{"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": f"here is the meeting transcript:\n\n{transcript}"}],
        response_format={"type": "json_object"}
    )
    
    content = response.choices[0].message.content
    return json.loads(content)

# def validate_notes_shape ():


def verify_quotes (transcript: str, notes: dict) -> dict:
    for item in notes["action_items"]:
        item["quote_verified"] = item["supporting_quote"].strip() in transcript
    return notes